AWSTemplateFormatVersion: '2010-09-09'
Description: WAF ACL for the serverless application (for us-east-1 region)

Resources:
  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: TodoAppWebACL
      Scope: CLOUDFRONT
      DefaultAction: { Allow: {} }
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: TodoAppWebACLMetric
        SampledRequestsEnabled: true
      Rules:
        - Name: AWS-AWSManagedRulesCommonRuleSet
          Priority: 1
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          OverrideAction: { None: {} }
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesCommonRuleSetMetric
            SampledRequestsEnabled: true

Outputs:
  WebACLArn:
    Description: "ARN of the WAF WebACL"
    Value: !GetAtt WebACL.Arn
    Export:
      Name: waf-todo-app-prod-WebACLArn